services:
  app:
    image: analytics-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8001
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: docker-compose.yaml